name: timeago_flutter
description: Timeago Widget for Flutter to create fuzzy timestamps. (e.g. "15 minutes ago").
version: 1.0.1
homepage: https://github.com/andresaraujo/timeago.dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  timeago:
    git:
      url: git://github.com/andersonmendess/timeago.dart
      ref: timeago
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
